volumes:
  outline:
    name: outline
  outline-postgres:
    name: outline-postgres

networks:
  default:
    name: outline

services:
  outline:
    extends:
      file: docker-compose.prod.yml
      service: outline
    image: !reset
    pull_policy: !reset
    build:
      dockerfile: !reset
    depends_on:
      - outline-postgres
      - outline-redis
      - outline-oidc
    volumes:
      - ./translation/ru.json:/opt/outline/shared/i18n/locales/ru_RU/translation.json

  outline-oidc:
    extends:
      file: docker-compose.prod.yml
      service: outline-oidc

  outline-redis:
    extends:
      file: docker-compose.prod.yml
      service: outline-redis

  outline-postgres:
    extends:
      file: docker-compose.prod.yml
      service: outline-postgres
