#!/usr/bin/env bash

WORKDIR="$(dirname "$(readlink -f "${0}")")"

if ! git diff --cached --quiet --submodule=diff -- ./outline; then
    python "$WORKDIR/update_readme.py"
    git add ./README.md
    exit 0
else
    exit 0
fi
